#!/usr/bin/env ansible-playbook
---
- name: Undercloud part of gnocchi testing
  hosts: undercloud-0
  tasks:
      - name: Clone git repo to undercloud
        git:
          repo: "https://github.com/sashkavyshka/gnocchi_auto.git"
          dest: "~/gnocchi_auto"

      - name: Copy overcloudrc to controller
        shell: |
          source ~/stackrc;
          ssh-keyscan $(openstack server list -f value | grep controller-0 | cut -d " " -f 4 | cut -d "=" -f 2) >  ~/.ssh/known_hosts;
          scp overcloudrc heat-admin@$(openstack server list -f value | grep controller-0 | cut -d " " -f 4 | cut -d "=" -f 2):stackrc

      - name: Change permissions
        file:
          path: gnocchi_auto
          mode: 0770

      - name: Run python tests on overcloud
        shell: |
          source ~/overcloudrc;
          echo -n "RHELOSP_6835 " >> output.txt;
          python gnocchi_auto/RHELOSP_6835.py;
          out=$(echo $?);
          if [out=0]; then
            echo "deployment completed" > /tmp/RHELOSP-6835;
          fi
          echo -n "RHELOSP_6841 " >> output.txt;
          python gnocchi_auto/RHELOSP_6841.py;
          out=$(echo $?);
          if [out=0]; then
            echo "deployment completed" > /tmp/RHELOSP-6841;
          fi
          python gnocchi_auto/RHELOSP_6842.py;
          out=$(echo $?);
          if [out=0]; then
            echo "deployment completed" > /tmp/RHELOSP-6842;
          fi
          python gnocchi_auto/RHELOSP_6844.py;
          out=$(echo $?);
          if [out=0]; then
            echo "deployment completed" > /tmp/RHELOSP-6844;
          fi
          python gnocchi_auto/RHELOSP_7043.py;
          out=$(echo $?);
          if [out=0]; then
            echo "deployment completed" > /tmp/RHELOSP-7043;
          fi
          python gnocchi_auto/RHELOSP_7044.py;
          out=$(echo $?);
          if [out=0]; then
            echo "deployment completed" > /tmp/RHELOSP-7044;
          fi
